### ISSUE TITLE
Use Absolute Links in Item-Descriptions in the Feed

### ISSUE THREAD

**Issue by ephes** [ephes/django-cast#125]
The description of a podcast episode in the feed consists of the html rendered when navigating to the detail page of an episode. It's quoted to not break the feed. But the links in this html are relative. Which makes sense for a detail page. But what should podcast clients do which try to render the description?

Display the links, but they don't work when you click on them:

- antennapod (android)
- castro (iOS)

Just don't show a link:

- Apple podcasts (iOS)

The best way to handle this is probably to render absolute links for the description of a feed item in the podcast feed. Thx @faulhaberben for reporting this!

**Comment by faulhaberben** [comment]
What I reported only concerns the last link underneath the shownotes. Looking at https://python-podcast.de/show/ I find it as an `<a href="/show/freelancing/"> Shownotes | Kommentare | Permalink </a>` . \
This used to be displayed in antennapod (android) but obviously without linking to the absolut URL but resolving to `localhost` instead. \
Note: The links _in_ the shownotes still work fine with the fixes but they did so before, too (antennapod).

**Comment by faulhaberben** [comment]
BTW: I code searched for "`Shownotes | Kommentare | Permalink`" but only found it in a experimental(?) notebook:\
https://github.com/ephes/django-cast/blob/899f23287c4bbabc039f57bf711c8e26a46bc434/notebooks/twitter/twitter_player_card.ipynb#L43

**Comment by ephes** [comment]
> What I reported only concerns the last link underneath the shownotes. Looking at https://python-podcast.de/show/ I find it as an `<a href="/show/freelancing/"> Shownotes | Kommentare | Permalink </a>` . This used to be displayed in antennapod (android) but obviously without linking to the absolut URL but resolving to `localhost` instead. However, now it is not displayed anymore. Thus, there is no link to the website. Note: The links _in_ the shownotes still work fine with the fixes but they did so before, too (antennapod).

There are different versions of a post rendered for the overview page of a blog (when you look at https://python-podcast.de/show/) and the detail view, when you clicked on the detail link. Shownotes and comments are only displayed on the detail page, for example. It makes sense for the overview representation to include a link to the detail variant, because there's additional information. But it doesn't make sense to include the detail page link again  on the detail page. This was just a bug. And it ended up in the feed, becaus I use the detail variant as the description of the post in the feed.

A link to the detail page of the post should still be included in the description. Both title and date should link to the detail version of the episode. And this time it should also work in antennapod, since the urls should be absolute now. If it does not work, I'll reopen the bug 😁.

**Comment by faulhaberben** [comment]
I can confirm that it works (antennapod) as you describe above. It is not obvious, though, that one can comment via clicking title or date.

**Comment by ephes** [comment]
> I can confirm that it works (antennapod) as you describe above. It is not obvious, though, that one can comment via clicking title or date.

You are right. I'll add a "click here to comment"  hint. We'll see whether it's a good idea to encourage people to comment - this could be a double edged sword, but lets just try it 😼.
