### ISSUE TITLE
Fix Pagination

### ISSUE THREAD

**Issue by ephes** [ephes/django-cast#66]
When there are more than x pages, the page numbers in the pagination are abbreviated with `...`. If you have 20 pages, there's no way to get to page 13 just by navigating, you have to change the url parameter to `page=13` by hand. Make it navigable. Ok, it's possible to go to `page=13` by using the `next` button, but it's very tedious.

Other things to fix:
- [x] If you click on `1` you stay on the same page, if you click on `next` you get to `2`
- [x] Make the link for  the current page number inactiv
- [x] Provide correct arguments for `get_elided_page_range`

**Comment by RentFreeMedia** [comment]
Hey there, good to see someone else working on podcast tools with Wagtail, I thought I was the only one!

I went to the trouble awhile back on how to hack up the Django core pagination to accommodate seasons, and at the time thought it worthy of a blog post writeup.  It was rather tricky to well... trick... the core Django paginator into handling arbitrary numbers without excessive queries.  

I never got around to revisiting this with the Django 3.2+ "fancy" indexes which can include additional data, but I think you could extend the functionality (or at least query efficiency) even more with those.

https://rentfree.media/posts/wagtail/pagination/django/2022-02-03-hacking-the-django-paginator.html

**Comment by ephes** [comment]
Hi Neal 😃,

your project looks really interesting. Seems like you got a lot of things done already, wow. This pagination issue here is a lot less complicated. I have yet to find the time to read through your article to be able to comment on your pagination problem.

Did you ever think about [serving the media files directly from Django](https://youtu.be/axWjD3Es9G8) over using nginx? I used the X-sendfile method too and it's kind of ok (although I didn't used signed URLs but just the response header) and then there's another option where nginx sends an auth request to a backend URL and serves files based on the response.

**Comment by ephes** [comment]
> 



> so you have to put the auth token in the URL itself if you want to keep things simple for paying subscription users (they copy and paste a URL into iTunes or whatever other phone app and their subscription podcast feed "just works").

Did you have a look at [django-sesame](https://github.com/aaugustin/django-sesame)? I agree, for paid subscriptions the authentication has to be included in the URL.

**Comment by ephes** [comment]
> The trickiest problem I had to solve in all of the stuff I built around Wagtail and Django was the media X-Sendfile serving stuff and... the paginator 😂

Hi Neal,

ok - I managed to read your pagination post, but I have to admit I probably still don't understand it. Is it possible that you just want to be able to filter by season?

Imagine you want to limit the episodes you show in a list to a certain date range. Or you did a full text search for some terms. In all of those cases you still want to be able to paginate through the list of episodes, right? So why are seasons different? You could also use a `Paginator(seasons)` to make the season filter look like item based pagination, but this is pure display logic, right?

**Comment by ephes** [comment]
> https://rentfree.media/posts/wagtail/pagination/django/2022-02-03-hacking-the-django-paginator.html

@RentFreeMedia One additional thing that crossed my mind while reading your post: yes there are [paged feeds](https://www.rfc-editor.org/rfc/rfc5005#section-3) in rss. If you have a long running podcast, your feed will get huge over time otherwise.
